<%
' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.
On Error Resume Next

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("name_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "name", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(3)
	Dim arFormDBFields0(3)

	arFormFields0(0) = "S1"
	arFormDBFields0(0) = "say"
	arFormFields0(1) = "name_please"
	arFormDBFields0(1) = "name"
	arFormFields0(2) = "your_hair"
	arFormDBFields0(2) = "hair"

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0

	If Request.ServerVariables("REMOTE_HOST") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("REMOTE_HOST"), "love2"
	End If
	FP_SaveFieldToDB fp_rs, Now, "time"
	If Request.ServerVariables("REMOTE_USER") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("REMOTE_USER"), "user"
	End If

	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Response.Redirect "../categories/music.asp"

End If
End If

%>
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>?</title>
</head>

<body bgcolor="#FFFFFF">

<p align="center"><font face="Arial" size="2"><img border="0" src="../images/storefront/honchie_plain.jpg"></font></p>
<p align="center">&nbsp;</p>
<form method="POST" action="who.asp" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" startspan SuggestedExt="asp"
  U-ASP-Include-Url="../_fpclass/fpdbform.inc" S-DataConnection="name"
  S-RecordSource="name" U-Database-URL="name.mdb"
  U-Confirmation-Url="../categories/music.asp"
  S-Builtin-Fields="REMOTE_HOST Timestamp REMOTE_USER"
  S-Builtin-DBFields="love2 time user" S-Form-Fields="S1 name_please your_hair"
  S-Form-DBFields="say name hair" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../_fpclass/fpdbform.inc"--><!--webbot
  bot="SaveDatabase" endspan i-checksum="34604" -->
  <p align="center"><font face="Arial" size="2">What's your name?<br>
  <br>
  <input type="text" name="name_please" size="30"></font></p>
  <p align="center">&nbsp;</p>
  <p align="center"><font face="Arial" size="2">What's your email?<br>
  <br>
  <input name="your_hair" size="30"></font></p>
  <p align="center">&nbsp;</p>
  <p align="center"><font face="Arial" size="2">What's your request?<br>
  <br>
  <textarea rows="10" name="S1" cols="50"></textarea><br>
  <br>
  <input type="submit" value="Send" name="hair"></font></p>
</form>

</body>

</html>
