<%
' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.
On Error Resume Next

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("albumname_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "album_name", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(4)
	Dim arFormDBFields0(4)

	arFormFields0(0) = "album_name"
	arFormDBFields0(0) = "album_name"
	arFormFields0(1) = "email"
	arFormDBFields0(1) = "email"
	arFormFields0(2) = "explanation"
	arFormDBFields0(2) = "explanation"
	arFormFields0(3) = "name"
	arFormDBFields0(3) = "name"

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0

	If Request.ServerVariables("HTTP_USER_AGENT") <> "" Then
		FP_SaveFieldToDB fp_rs, Request.ServerVariables("HTTP_USER_AGENT"), "computer ID"
	End If
	FP_SaveFieldToDB fp_rs, Now, "timestamp"

	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Response.Redirect "confirmation.asp"

End If
End If

%>
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>?</title>
</head>

<body bgcolor="#FFFFFF">

<p align="center"><font face="Arial" size="2"><img border="0" src="../images/storefront/honchie_plain.jpg"></font></p>
<p align="center">&nbsp;</p>
<form method="POST" action="album_entry.asp" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" SuggestedExt="asp"
  U-ASP-Include-Url="../_fpclass/fpdbform.inc" S-DataConnection="albumname"
  S-RecordSource="album_name" U-Database-URL="album_name.mdb"
  U-Confirmation-Url="confirmation.asp"
  S-Builtin-Fields="HTTP_USER_AGENT Timestamp"
  S-Builtin-DBFields="computer\ ID timestamp"
  S-Form-Fields="album_name email explanation name"
  S-Form-DBFields="album_name email explanation name" startspan --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../_fpclass/fpdbform.inc"--><!--webbot bot="SaveDatabase" endspan i-checksum="34604" -->
  <p align="center"><font face="Arial" size="2">First off, what's your damn
  name?</font></p>
  <p align="center"><font face="Arial" size="2"><input type="text" name="name" size="30"><br>
  <br>
  <br>
  <br>
  What should Honchie's debut album be named?<br>
  <br>
  <input type="text" name="album_name" size="30"></font></p>
  <p align="center">&nbsp;</p>
  <p align="center"><font face="Arial" size="2">Is there a picture? What does it
  all mean, jack-ass? Explain!<br>
  <br>
  <textarea rows="10" name="explanation" cols="50"></textarea><br>
  <br>
  <br>
  <br>
  Okay genius, what's your email?<br>
  <br>
  <input name="email" size="30"><br>
  <br>
  <br>
  <br>
  <input type="submit" value="Send" name="hair"></font></p>
</form>

</body>

</html>
